collections_config:
  pages:
    _enabled_editors:
      - visual
  posts:
    _enabled_editors:
      - content
      - visual
_inputs:
  title: "HUGO-Amplify_TEST"
    type: text
    comment: The title of your page.
  content:
    type: markdown

   

# Base path to your site source files
source: github.com/gvhconnect/hugo-amplify-test

# The subpath your built output files are mounted at
base_url: main.dj1h7qwffogh3.amplifyapp.com/

# Populates collections for navigation and metadata in the editor
collections_config:
  people:
    # Base path for files in this collection, relative to source
    path: content/people

    # Whether this collection produces output files or not
    output: true

    # Collection-level configuration
    name: Personnel
    _enabled_editors:
      - data
  posts:
    path: _posts
    output: true
  pages:
    name: Main pages

# Generates the data for select and multiselect inputs matching these names
data_config:
  # Populates data with authors from an data file with the matching name
  authors: true
  offices: true

paths:
  # The default location for newly uploaded files, relative to source
  uploads: assets/uploads

  # The path to site data files, relative to source
  data: _data

  # The path to site layout files, relative to source
  layouts: _layouts
